[package]
name = "caesars-palace-nes"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
pretty_assertions = "1.3.0"

[dev-dependencies]
clap = { version = "4.0.32", features = ["derive"] }
parse_int = "0.6.0"
